name: Deploy to w7s

on:
  push:
    branches:
      - Main
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: w7s-io/w7s-cloud@v1
        with:
          token: ${{ github.token }}
          install-command: npm ci
          build-command: npm run build
